filebeat.inputs:
- type: filestream
  enabled: true
  parsers:
    - multiline:
        type: pattern
        pattern: '^[[:space:]]Event:'
        negate: false
        match: after
  include_lines: ['Event:']
  paths:
   - "/usr/share/logs_loc/wso2carbon*.log"
output.logstash:
  hosts: ["logstash:5044"]